In [38]:
import pandas as pd

In [51]:
f1=pd.read_csv(r"F:\4-1 Files\Udemy - Data Analysis with Pandas and Python\1. Installation and Setup\1.1 pandas.zip\fortune1000.csv",index_col="Rank")
Sectors=f1.groupby("Sector")
f1.head(3)

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000

In [41]:
type(Sectors)

pandas.core.groupby.groupby.DataFrameGroupBy

In [7]:
f1.head(3)
f1["Sector"].value_counts()

Financials                      139
Energy                          122
Technology                      102
Retailing                        80
Health Care                      75
Business Services                51
Industrials                      46
Food, Beverages & Tobacco        43
Materials                        43
Wholesalers                      40
Transportation                   36
Chemicals                        30
Household Products               28
Engineering & Construction       26
Media                            25
Hotels, Resturants & Leisure     25
Motor Vehicles & Parts           24
Aerospace & Defense              20
Food and Drug Stores             15
Apparel                          15
Telecommunications               15
Name: Sector, dtype: int64

In [42]:
len(Sectors)
Sectors.size()

Sector                      Industry
Aerospace & Defense         Aerospace and Defense                             20
Apparel                     Apparel                                           15
Business Services           Advertising, marketing                             2
                            Diversified Outsourcing Services                  14
                            Education                                          3
                            Financial Data Services                           19
                            Miscellaneous                                      3
                            Temporary Help                                     5
                            Waste Management                                   5
Chemicals                   Chemicals                                         30
Energy                      Energy                                            14
                            Mining, Crude-Oil Production                      28
                            Miscellaneous                                      1
                            Oil and Gas Equipment, Services                    9
                            Petroleum Refining                                17
                            Pipelines                                         12
                            Utilities: Gas and Electric                       41
Engineering & Construction  Engineering, Construction                         14
                            Homebuilders                                      12
Financials                  Commercial Banks                                  28
                            Diversified Financials                            15
                            Insurance: Life, Health (Mutual)                  10
                            Insurance: Life, Health (stock)                   18
                            Insurance: Property and Casualty (Mutual)          7
                            Insurance: Property and Casualty (Stock)          28
                            Real estate                                       15
                            Securities                                        18
Food and Drug Stores        Food and Drug Stores                              15
Food, Beverages & Tobacco   Beverages                                          9
                            Food Consumer Products                            20
                                                                              ..
Materials                   Metals                                            14
                            Miscellaneous                                      1
                            Packaging, Containers                             16
Media                       Entertainment                                     18
                            Publishing, Printing                               7
Motor Vehicles & Parts      Motor Vehicles and Parts                          24
Retailing                   Automotive Retailing, Services                    10
                            General Merchandisers                             10
                            Specialty Retailers: Apparel                      18
                            Specialty Retailers: Other                        42
Technology                  Computer Peripherals                               4
                            Computer Software                                 14
                            Computers, Office Equipment                        7
                            Information Technology Services                   13
                            Internet Services and Retailing                   15
                            Network and Other Communications Equipment        14
                            Scientific,Photographic and Control Equipment     12
                            Semiconductors and Other Electronic Components    23
Telecommunications          Telecommunications                                15
Transportation              Airlines                                           9
                            Mail, Package, and Freight Delivery                2
                            Miscellaneous                                      1
                            Railroads                                          5
                            Transportation Equipment                           5
                            Transportation and Logistics                       5
                            Trucking, Truck Leasing                            9
Wholesalers                 Miscellaneous                                      1
                            Wholesalers: Diversified                          25
                            Wholesalers: Electronics and Office Equipment      8
                            Wholesalers: Food and Grocery                      6
Length: 79, dtype: int64

In [14]:
Sectors.first()
Sectors.last()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Delta Tucker Holdings,Aerospace and Defense,"McLean, VA",1923,-133,12000
Apparel,Guess,Apparel,"Los Angeles, CA",2204,82,13500
Business Services,DeVry Education Group,Education,"Downers Grove, IL",1910,140,11770
Chemicals,H.B. Fuller,Chemicals,"St. Paul, MN",2084,87,4425
Energy,Portland General Electric,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
Engineering & Construction,MDC Holdings,Homebuilders,"Denver, CO",1909,66,1225
Financials,New York Community Bancorp,Commercial Banks,"Westbury, NY",1902,-47,3448
Food and Drug Stores,Fred’s,Food and Drug Stores,"Memphis, TN",2151,-7,7103
"Food, Beverages & Tobacco",Alliance One International,Tobacco,"Morrisville, NC",2066,-15,6835
Health Care,Providence Service,Health Care: Pharmacy and Other Services,"Tucson, AZ",1987,84,9072
"Hotels, Resturants & Leisure",Wendy’s,Food Services,"Dublin, OH",1896,161,21200
Household Products,Revlon,Household and Personal Products,"New York, NY",1914,56,5700
Industrials,Briggs & Stratton,Industrial Machinery,"Wauwatosa, WI",1895,46,5480
Materials,Schnitzer Steel Industries,Metals,"Portland, OR",1924,-197,2955
Media,Cenveo,"Publishing, Printing","Stamford, CT",1921,-31,7300
Motor Vehicles & Parts,Allison Transmission Holdings,Motor Vehicles and Parts,"Indianaoplis, IN",1986,182,2700
Retailing,99 Cents Only Stores,Specialty Retailers: Other,"Commerce, CA",1999,-232,18200
Technology,F5 Networks,Network and Other Communications Equipment,"Seattle, WA",1920,365,4178
Telecommunications,Equinix,Telecommunications,"Redwood City, CA",2726,188,5042
Transportation,Roadrunner Transportation Systems,Transportation and Logistics,"Cudahy, WI",1995,48,4502
Wholesalers,BlueLinx Holdings,Wholesalers: Diversified,"Atlanta, GA",1917,-12,1600

In [15]:
Sectors.head(3)

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
6,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,"Minnetonka, MN",157107,5813,200000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
9,Ford Motor,Motor Vehicles & Parts,Motor Vehicles and Parts,"Dearborn, MI",149558,7373,199000
10,AT&T,Telecommunications,Telecommunications,"Dallas, TX",146801,13345,281450
11,General Electric,Industrials,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
12,AmerisourceBergen,Health Care,Wholesalers: Health Care,"Chesterbrook, PA",135962,-135,17000
13,Verizon,Telecommunications,Telecommunications,"New York, NY",131620,17879,177700
14,Chevron,Energy,Petroleum Refining,"San Ramon, CA",131118,4587,61500
15,Costco,Retailing,Specialty Retailers: Other,"Issaquah, WA",116199,2377,161000
16,Fannie Mae,Financials,Diversified Financials,"Washington, DC",110359,10954,7300
17,Kroger,Food and Drug Stores,Food and Drug Stores,"Cincinnati, OH",109830,2039,431000
18,Amazon.com,Technology,Internet Services and Retailing,"Seattle, WA",107006,596,230800
19,Walgreens Boots Alliance,Food and Drug Stores,Food and Drug Stores,"Deerfield, IL",103444,4220,302500
20,HP,Technology,"Computers, Office Equipment","Palo Alto, CA",103355,4554,287000
23,J.P. Morgan Chase,Financials,Commercial Banks,"New York, NY",101006,24442,234598
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
28,Home Depot,Retailing,Specialty Retailers: Other,"Atlanta, GA",88519,7009,385000
30,Phillips 66,Energy,Petroleum Refining,"Houston, TX",87169,4227,14000
34,Procter & Gamble,Household Products,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
37,Comcast,Telecommunications,Telecommunications,"Philadelphia, PA",74510,8163,153000
41,Archer Daniels Midland,"Food, Beverages & Tobacco",Food Production,"Chicago, IL",67702,1849,32300
44,PepsiCo,"Food, Beverages & Tobacco",Food Consumer Products,"Purchase, NY",63056,5452,263000
45,United Technologies,Aerospace & Defense,Aerospace and Defense,"Farmington, CT",61047,7608,197200
48,UPS,Transportation,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
...,...,...,...,...,...,...,...
58,FedEx,Transportation,"Mail, Package, and Freight Delivery","Memphis, TN",47453,1050,323035
59,Caterpillar,Industrials,Construction and Farm Machinery,"Peoria, IL",47011,2102,112200
60,Lockheed Martin,Aerospace & Defense,Aerospace and Defense,"Bethesda, MD",46132,3605,126000
62,Coca-Cola,"Food, Beverages & Tobacco",Beverages,"Atlanta, GA",44294,7351,123200
64,Ingram Micro,Wholesalers,Wholesalers: Electronics and Office Equipment,"Irvine, CA",43026,215,27700
67,American Airlines Group,Transportation,Airlines,"Fort Worth, TX",40990,7610,118500
70,Johnson Controls,Motor Vehicles & Parts,Motor Vehicles and Parts,"Milwaukee, WI",40204,1563,139000
75,Honeywell International,Industrials,"Electronics, Electrical Equip.","Morris Plains, NJ",38581,4768,129000
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
92,World Fuel Services,Wholesalers,Wholesalers: Diversified,"Miami, FL",30380,187,4700
96,Twenty-First Century Fox,Media,Entertainment,"New York, NY",28987,8306,20500
99,Time Warner,Media,Entertainment,"New York, NY",28118,3833,24800
101,DuPont,Chemicals,Chemicals,"Wilmington, DE",27940,1953,52000
109,McDonald’s,"Hotels, Resturants & Leisure",Food Services,"Oak Brook, IL",25413,4529,420000
126,Alcoa,Materials,Metals,"New York, NY",22534,-322,60000
127,International Paper,Materials,"Packaging, Containers","Memphis, TN",22365,938,56000
144,ManpowerGroup,Business Services,Temporary Help,"Milwaukee, WI",19330,419,27000
146,Starbucks,"Hotels, Resturants & Leisure",Food Services,"Seattle, WA",19163,2757,238000
151,Kimberly-Clark,Household Products,Household and Personal Products,"Irving, TX",18591,1013,43000
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
156,AECOM,Engineering & Construction,"Engineering, Construction","Los Angeles, CA",17990,-155,92000
170,Nucor,Materials,Metals,"Charlotte, NC",16439,358,23700
174,Colgate-Palmolive,Household Products,Household and Personal Products,"New York, NY",16034,1384,37900
182,PPG Industries,Chemicals,Chemicals,"Pittsburgh, PA",15330,1406,46600
186,Omnicom Group,Business Services,"Advertising, marketing","New York, NY",15134,1094,74900
195,Marriott International,"Hotels, Resturants & Leisure","Hotels, Casinos, Resorts","Bethesda, MD",14486,859,127500
199,Aramark,Business Services,Diversified Outsourcing Services,"Philadelphia, PA",14329,236,216500
231,VF,Apparel,Apparel,"Greensboro, NC",12377,1232,64000
235,Jacobs Engineering Group,Engineering & Construction,"Engineering, Construction","Pasadena, CA",12115,303,56950
340,PVH,Apparel,Apparel,"New York, NY",8020,572,26200

In [19]:
Sectors.groups
f1.loc[45]

Company        United Technologies
Sector         Aerospace & Defense
Industry     Aerospace and Defense
Location            Farmington, CT
Revenue                      61047
Profits                       7608
Employees                   197200
Name: 45, dtype: object

In [25]:
Sectors.get_group("Energy")
Sectors.get_group("Technology").head(3)

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
18,Amazon.com,Technology,Internet Services and Retailing,"Seattle, WA",107006,596,230800
20,HP,Technology,"Computers, Office Equipment","Palo Alto, CA",103355,4554,287000

In [27]:
Sectors.max().head(3)

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Woodward,Aerospace and Defense,"Wichita, KS",96114,7608,197200
Apparel,Wolverine World Wide,Apparel,"Winston-Salem, NC",30601,3273,65300
Business Services,Western Union,Waste Management,"Troy, MI",19330,6328,216500

In [36]:
Sectors.sum().head(3)

                     Revenue  Profits  Employees
Sector
Aerospace & Defense   357940    28742     968057
Apparel                95968     8236     346397
Business Services     272195    28227    1361050

In [34]:
Sectors.get_group("Apparel")["Profits"].mean()

549.0666666666667

In [37]:
Sectors["Revenue"].sum()
Sectors["Employees"].sum()

Sector
Aerospace & Defense              968057
Apparel                          346397
Business Services               1361050
Chemicals                        463651
Energy                          1188927
Engineering & Construction       406708
Financials                      3359948
Food and Drug Stores            1395398
Food, Beverages & Tobacco       1211632
Health Care                     2678289
Hotels, Resturants & Leisure    2484245
Household Products               646038
Industrials                     1545229
Materials                        638123
Media                            550314
Motor Vehicles & Parts          1082560
Retailing                       6227629
Technology                      3578949
Telecommunications               832468
Transportation                  1536793
Wholesalers                      525597
Name: Employees, dtype: int64

In [44]:
Sectors.sum()

                                                                           Revenue  \
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                            357940
Apparel                    Apparel                                           95968
Business Services          Advertising, marketing                            22748
                           Diversified Outsourcing Services                  64829
                           Education                                          7485
                           Financial Data Services                          100778
                           Miscellaneous                                     11185
                           Temporary Help                                    34716
                           Waste Management                                  30454
Chemicals                  Chemicals                                        243897
Energy                     Energy                                            67749
                           Mining, Crude-Oil Production                     176435
                           Miscellaneous                                      3159
                           Oil and Gas Equipment, Services                   82827
                           Petroleum Refining                               705472
                           Pipelines                                        138756
                           Utilities: Gas and Electric                      343411
Engineering & Construction Engineering, Construction                         99774
                           Homebuilders                                      54209
Financials                 Commercial Banks                                 623669
                           Diversified Financials                           327075
                           Insurance: Life, Health (Mutual)                 181336
                           Insurance: Life, Health (stock)                  245551
                           Insurance: Property and Casualty (Mutual)        143682
                           Insurance: Property and Casualty (Stock)         548027
                           Real estate                                       62748
                           Securities                                        85071
Food and Drug Stores       Food and Drug Stores                             483769
Food, Beverages & Tobacco  Beverages                                         79396
                           Food Consumer Products                           238954
...                                                                            ...
Materials                  Metals                                            99925
                           Miscellaneous                                      6070
                           Packaging, Containers                            105965
Media                      Entertainment                                    186276
                           Publishing, Printing                              34488
Motor Vehicles & Parts     Motor Vehicles and Parts                         482540
Retailing                  Automotive Retailing, Services                   113823
                           General Merchandisers                            684320
                           Specialty Retailers: Apparel                     122975
                           Specialty Retailers: Other                       543958
Technology                 Computer Peripherals                              48950
                           Computer Software                                179112
                           Computers, Office Equipment                      353781
                           Information Technology Services                  166067
                           Internet Services and Retailing                  259136
                           Network and Other Communications Equipment       125697
                           Scientific,Photographic and Control Equipment     65832
                           Semiconductors and Other Electronic Components   179025
Telecommunications         Telecommunications                               461834
Transportation             Airlines                                         158948
                           Mail, Package, and Freight Delivery              105816
                           Miscellaneous                                      2148
                           Railroads                                         48554
                           Transportation Equipment                          23855
                           Transportation and Logistics                      33237
                           Trucking, Truck Leasing                           35950
Wholesalers                Miscellaneous                                      8982
                           Wholesalers: Diversified                         176138
                           Wholesalers: Electronics and Office Equipment    147906
                           Wholesalers: Food and Grocery                    111774

                                                                           Profits  \
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                             28742
Apparel                    Apparel                                            8236
Business Services          Advertising, marketing                             1549
                           Diversified Outsourcing Services                   4305
                           Education                                            69
                           Financial Data Services                           17456
                           Miscellaneous                                      2130
                           Temporary Help                                     1000
                           Waste Management                                   1718
Chemicals                  Chemicals                                         22628
Energy                     Energy                                           -13038
                           Mining, Crude-Oil Production                    -124555
                           Miscellaneous                                       476
                           Oil and Gas Equipment, Services                   -4047
                           Petroleum Refining                                31888
                           Pipelines                                          5814
                           Utilities: Gas and Electric                       30015
Engineering & Construction Engineering, Construction                          1765
                           Homebuilders                                       3539
Financials                 Commercial Banks                                 129760
                           Diversified Financials                            28548
                           Insurance: Life, Health (Mutual)                   5601
                           Insurance: Life, Health (stock)                   19731
                           Insurance: Property and Casualty (Mutual)          8031
                           Insurance: Property and Casualty (Stock)          44803
                           Real estate                                        9480
                           Securities                                        14255
Food and Drug Stores       Food and Drug Stores                              16759
Food, Beverages & Tobacco  Beverages                                         11698
                           Food Consumer Products                            19263
...                                                                            ...
Materials                  Metals                                            -2241
                           Miscellaneous                                         7
                           Packaging, Containers                              4445
Media                      Entertainment                                     25686
                           Publishing, Printing                              -1339
Motor Vehicles & Parts     Motor Vehicles and Parts                          25898
Retailing                  Automotive Retailing, Services                     2550
                           General Merchandisers                             20137
                           Specialty Retailers: Apparel                       4583
                           Specialty Retailers: Other                        20560
Technology                 Computer Peripherals                               3975
                           Computer Software                                 26457
                           Computers, Office Equipment                       58433
                           Information Technology Services                   16402
                           Internet Services and Retailing                   22232
                           Network and Other Communications Equipment        18907
                           Scientific,Photographic and Control Equipment      9346
                           Semiconductors and Other Electronic Components    24721
Telecommunications         Telecommunications                                48637
Transportation             Airlines                                          23800
                           Mail, Package, and Freight Delivery                5894
                           Miscellaneous                                       227
                           Railroads                                          9005
                           Transportation Equipment                           2438
                           Transportation and Logistics                        895
                           Trucking, Truck Leasing                            1910
Wholesalers                Miscellaneous                                        17
                           Wholesalers: Diversified                           5193
                           Wholesalers: Electronics and Office Equipment      1857
                           Wholesalers: Food and Grocery                      1166

                                                                           Employees
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                              968057
Apparel                    Apparel                                            346397
Business Services          Advertising, marketing                             124100
                           Diversified Outsourcing Services                   708330
                           Education                                           46755
                           Financial Data Services                            264926
                           Miscellaneous                                       37720
                           Temporary Help                                      60020
                           Waste Management                                   119199
Chemicals                  Chemicals                                          463651
Energy                     Energy                                              70072
                           Mining, Crude-Oil Production                       149110
                           Miscellaneous                                        6700
                           Oil and Gas Equipment, Services                    225795
                           Petroleum Refining                                 244880
                           Pipelines                                           72141
                           Utilities: Gas and Electric                        420229
Engineering & Construction Engineering, Construction                          368104
                           Homebuilders                                        38604
Financials                 Commercial Banks                                  1539024
                           Diversified Financials                             329114
                           Insurance: Life, Health (Mutual)                    58801
                           Insurance: Life, Health (stock)                    202233
                           Insurance: Property and Casualty (Mutual)          133148
                           Insurance: Property and Casualty (Stock)           794123
                           Real estate                                        160579
                           Securities                                         142926
Food and Drug Stores       Food and Drug Stores                              1395398
Food, Beverages & Tobacco  Beverages                                          199107
                           Food Consumer Products                             665439
...                                                                              ...
Materials                  Metals                                             193559
                           Miscellaneous                                          52
                           Packaging, Containers                              333446
Media                      Entertainment                                      383564
                           Publishing, Printing                               166750
Motor Vehicles & Parts     Motor Vehicles and Parts                          1082560
Retailing                  Automotive Retailing, Services                     174974
                           General Merchandisers                             3408100
                           Specialty Retailers: Apparel                       770543
                           Specialty Retailers: Other                        1874012
Technology                 Computer Peripherals                               175259
                           Computer Software                                  388796
                           Computers, Office Equipment                        468085
                           Information Technology Services                    985639
                           Internet Services and Retailing                    430855
                           Network and Other Communications Equipment         299310
                           Scientific,Photographic and Control Equipment      231501
                           Semiconductors and Other Electronic Components     599504
Telecommunications         Telecommunications                                 832468
Transportation             Airlines                                           391601
                           Mail, Package, and Freight Delivery                664275
                           Miscellaneous                                        4200
                           Railroads                                          121844
                           Transportation Equipment                            59726
                           Transportation and Logistics                       124691
                           Trucking, Truck Leasing                            170456
Wholesalers                Miscellaneous                                        9200
                           Wholesalers: Diversified                           233831
                           Wholesalers: Electronics and Office Equipment      166661
                           Wholesalers: Food and Grocery                      115905

[79 rows x 3 columns]

In [49]:
Sectors.agg({"Revenue":"sum",
             "Profits":"sum",
             "Employees":"mean"})

                              Revenue  Profits     Employees
Sector
Aerospace & Defense            357940    28742  48402.850000
Apparel                         95968     8236  23093.133333
Business Services              272195    28227  26687.254902
Chemicals                      243897    22628  15455.033333
Energy                        1517809   -73447   9745.303279
Engineering & Construction     153983     5304  15642.615385
Financials                    2217159   260209  24172.287770
Food and Drug Stores           483769    16759  93026.533333
Food, Beverages & Tobacco      555967    51417  28177.488372
Health Care                   1614707   106114  35710.520000
Hotels, Resturants & Leisure   169546    20697  99369.800000
Household Products             234737    14428  23072.785714
Industrials                    497581    20764  33591.934783
Materials                      259145     4428  14840.069767
Media                          220764    24347  22012.560000
Motor Vehicles & Parts         482540    25898  45106.666667
Retailing                     1465076    47830  77845.362500
Technology                    1377600   180473  35087.735294
Telecommunications             461834    48637  55497.866667
Transportation                 408508    44169  42688.694444
Wholesalers                    444800     8233  13139.925000

In [50]:
Sectors.agg(["size","sum","mean"])

                             Revenue                        Profits          \
                                size      sum          mean    size     sum
Sector
Aerospace & Defense               20   357940  17897.000000      20   28742
Apparel                           15    95968   6397.866667      15    8236
Business Services                 51   272195   5337.156863      51   28227
Chemicals                         30   243897   8129.900000      30   22628
Energy                           122  1517809  12441.057377     122  -73447
Engineering & Construction        26   153983   5922.423077      26    5304
Financials                       139  2217159  15950.784173     139  260209
Food and Drug Stores              15   483769  32251.266667      15   16759
Food, Beverages & Tobacco         43   555967  12929.465116      43   51417
Health Care                       75  1614707  21529.426667      75  106114
Hotels, Resturants & Leisure      25   169546   6781.840000      25   20697
Household Products                28   234737   8383.464286      28   14428
Industrials                       46   497581  10816.978261      46   20764
Materials                         43   259145   6026.627907      43    4428
Media                             25   220764   8830.560000      25   24347
Motor Vehicles & Parts            24   482540  20105.833333      24   25898
Retailing                         80  1465076  18313.450000      80   47830
Technology                       102  1377600  13505.882353     102  180473
Telecommunications                15   461834  30788.933333      15   48637
Transportation                    36   408508  11347.444444      36   44169
Wholesalers                       40   444800  11120.000000      40    8233

                                          Employees
                                     mean      size      sum          mean
Sector
Aerospace & Defense           1437.100000        20   968057  48402.850000
Apparel                        549.066667        15   346397  23093.133333
Business Services              553.470588        51  1361050  26687.254902
Chemicals                      754.266667        30   463651  15455.033333
Energy                        -602.024590       122  1188927   9745.303279
Engineering & Construction     204.000000        26   406708  15642.615385
Financials                    1872.007194       139  3359948  24172.287770
Food and Drug Stores          1117.266667        15  1395398  93026.533333
Food, Beverages & Tobacco     1195.744186        43  1211632  28177.488372
Health Care                   1414.853333        75  2678289  35710.520000
Hotels, Resturants & Leisure   827.880000        25  2484245  99369.800000
Household Products             515.285714        28   646038  23072.785714
Industrials                    451.391304        46  1545229  33591.934783
Materials                      102.976744        43   638123  14840.069767
Media                          973.880000        25   550314  22012.560000
Motor Vehicles & Parts        1079.083333        24  1082560  45106.666667
Retailing                      597.875000        80  6227629  77845.362500
Technology                    1769.343137       102  3578949  35087.735294
Telecommunications            3242.466667        15   832468  55497.866667
Transportation                1226.916667        36  1536793  42688.694444
Wholesalers                    205.825000        40   525597  13139.925000

In [54]:
df = pd.DataFrame(columns=f1.columns)
df.head()

Empty DataFrame
Columns: [Company, Sector, Industry, Location, Revenue, Profits, Employees]
Index: []

In [56]:
for sector,data in Sectors:
    highest_profit_company=data.nlargest(1,"Profits")
    df=df.append(highest_profit_company)

In [57]:
df.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
45,United Technologies,Aerospace & Defense,Aerospace and Defense,"Farmington, CT",61047,7608,197200
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
204,Visa,Business Services,Financial Data Services,"Foster City, CA",13880,6328,11300
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600