In [1]:
import pandas as pd

In [71]:
bm=pd.read_csv(r"F:\4-1 Files\Udemy - Data Analysis with Pandas and Python\1. Installation and Setup\1.1 pandas.zip\bigmac.csv",parse_dates=["Date"],index_col=["Date","Country"])
bm.sort_index(inplace=True)
bm.head(3)

                      Price in US Dollars
Date       Country
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76

In [58]:
bm.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 652 entries, (2010-01-01 00:00:00, Argentina) to (2016-01-01 00:00:00, Vietnam)
Data columns (total 1 columns):
Price in US Dollars    652 non-null float64
dtypes: float64(1)
memory usage: 7.0+ KB

In [40]:
bm.set_index(["Date","Country"],inplace=True)

In [45]:
bm.sort_index(inplace=True)

In [46]:
bm.index.names

FrozenList(['Date', 'Country'])

In [65]:
bm.index.get_level_values(0)

AttributeError: 'DatetimeIndex' object has no attribute 'index'

In [68]:
bm.index.set_names(["Dt","Nation"],inplace=True)

In [72]:
bm.head(3)

                      Price in US Dollars
Date       Country
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76

In [91]:
bm.loc[("2015-07-01","Brazil"),:]

                    Price in US Dollars
Date       Country
2015-07-01 Brazil                  4.28

In [130]:
bm.transpose()

Date        Country
2010-01-01  Argentina       Price in US Dollars    1.84
            Australia       Price in US Dollars    3.98
            Brazil          Price in US Dollars    4.76
            Britain         Price in US Dollars    3.67
            Canada          Price in US Dollars    3.97
            Chile           Price in US Dollars    3.18
            China           Price in US Dollars    1.83
            Colombia        Price in US Dollars    3.91
            Costa Rica      Price in US Dollars    3.52
            Czech Republic  Price in US Dollars    3.71
            Denmark         Price in US Dollars    5.99
            Egypt           Price in US Dollars    2.38
            Euro area       Price in US Dollars    4.84
            Hong Kong       Price in US Dollars    1.91
            Hungary         Price in US Dollars    3.86
            Indonesia       Price in US Dollars    2.24
            Israel          Price in US Dollars    3.99
            Japan           Price in US Dollars    3.50
            Latvia          Price in US Dollars    3.09
            Lithuania       Price in US Dollars    2.87
            Malaysia        Price in US Dollars    2.08
            Mexico          Price in US Dollars    2.50
            New Zealand     Price in US Dollars    3.61
            Norway          Price in US Dollars    7.02
            Pakistan        Price in US Dollars    2.42
            Peru            Price in US Dollars    2.81
            Philippines     Price in US Dollars    2.21
            Poland          Price in US Dollars    2.86
            Russia          Price in US Dollars    2.34
            Saudi Arabia    Price in US Dollars    2.67
                                                   ...
2016-01-01  Italy           Price in US Dollars    4.30
            Japan           Price in US Dollars    3.12
            Malaysia        Price in US Dollars    1.82
            Mexico          Price in US Dollars    2.81
            Netherlands     Price in US Dollars    3.71
            New Zealand     Price in US Dollars    3.91
            Norway          Price in US Dollars    5.21
            Pakistan        Price in US Dollars    2.86
            Peru            Price in US Dollars    2.93
            Philippines     Price in US Dollars    2.79
            Poland          Price in US Dollars    2.37
            Portugal        Price in US Dollars    3.23
            Russia          Price in US Dollars    1.53
            Saudi Arabia    Price in US Dollars    3.20
            Singapore       Price in US Dollars    3.27
            South Africa    Price in US Dollars    1.77
            South Korea     Price in US Dollars    3.59
            Spain           Price in US Dollars    3.76
            Sri Lanka       Price in US Dollars    2.43
            Sweden          Price in US Dollars    5.23
            Switzerland     Price in US Dollars    6.44
            Taiwan          Price in US Dollars    2.08
            Thailand        Price in US Dollars    3.09
            Turkey          Price in US Dollars    3.41
            UAE             Price in US Dollars    3.54
            Ukraine         Price in US Dollars    1.54
            United States   Price in US Dollars    4.93
            Uruguay         Price in US Dollars    3.74
            Venezuela       Price in US Dollars    0.66
            Vietnam         Price in US Dollars    2.67
Length: 652, dtype: float64

In [99]:
bm.swaplevel(i=-1,j=-2).head(3)

                      Price in US Dollars
Country   Date
Argentina 2010-01-01                 1.84
Australia 2010-01-01                 3.98
Brazil    2010-01-01                 4.76

In [121]:
ws=pd.read_csv(r"F:\4-1 Files\Udemy - Data Analysis with Pandas and Python\1. Installation and Setup\1.1 pandas.zip\worldstats.csv",index_col=["country","year"])
ws.sort_index(inplace=True)
ws.head(3)

                  Population           GDP
country     year
Afghanistan 1960   8994793.0  5.377778e+08
            1961   9164945.0  5.488889e+08
            1962   9343772.0  5.466667e+08

In [122]:
ws.describe()
ws.shape
ws.axes

[MultiIndex(levels=[['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Arab World', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas, The', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Caribbean small states', 'Cayman Islands', 'Central African Republic', 'Central Europe and the Baltics', 'Chad', 'Channel Islands', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', 'Costa Rica', 'Cote d'Ivoire', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Early-demographic dividend', 'East Asia & Pacific', 'East Asia & Pacific (IDA & IBRD countries)', 'East Asia & Pacific (excluding high income)', 'Ecuador', 'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Euro area', 'Europe & Central Asia', 'Europe & Central Asia (IDA & IBRD countries)', 'Europe & Central Asia (excluding high income)', 'European Union', 'Faroe Islands', 'Fiji', 'Finland', 'Fragile and conflict affected situations', 'France', 'French Polynesia', 'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Heavily indebted poor countries (HIPC)', 'High income', 'Honduras', 'Hong Kong SAR, China', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA blend', 'IDA only', 'IDA total', 'Iceland', 'India', 'Indonesia', 'Iran, Islamic Rep.', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea, Rep.', 'Kosovo', 'Kuwait', 'Kyrgyz Republic', 'Lao PDR', 'Late-demographic dividend', 'Latin America & Caribbean', 'Latin America & Caribbean (excluding high income)', 'Latin America & the Caribbean (IDA & IBRD countries)', 'Latvia', 'Least developed countries: UN classification', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Low & middle income', 'Low income', 'Lower middle income', 'Luxembourg', 'Macao SAR, China', 'Macedonia, FYR', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia, Fed. Sts.', 'Middle East & North Africa', 'Middle East & North Africa (IDA & IBRD countries)', 'Middle East & North Africa (excluding high income)', 'Middle income', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North America', 'Norway', 'OECD members', 'Oman', 'Other small states', 'Pacific island small states', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Post-demographic dividend', 'Pre-demographic dividend', 'Puerto Rico', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia', 'Small states', 'Solomon Islands', 'Somalia', 'South Africa', 'South Asia', 'South Asia (IDA & IBRD)', 'South Sudan', 'Spain', 'Sri Lanka', 'St. Kitts and Nevis', 'St. Lucia', 'St. Vincent and the Grenadines', 'Sub-Saharan Africa', 'Sub-Saharan Africa (IDA & IBRD countries)', 'Sub-Saharan Africa (excluding high income)', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Upper middle income', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela, RB', 'Vietnam', 'Virgin Islands (U.S.)', 'West Bank and Gaza', 'World', 'Yemen, Rep.', 'Zambia', 'Zimbabwe'], [1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015]],

In [124]:
ws.stack().to_frame()

                                        0
country     year
Afghanistan 1960 Population  8.994793e+06
                 GDP         5.377778e+08
            1961 Population  9.164945e+06
                 GDP         5.488889e+08
            1962 Population  9.343772e+06
                 GDP         5.466667e+08
            1963 Population  9.531555e+06
                 GDP         7.511112e+08
            1964 Population  9.728645e+06
                 GDP         8.000000e+08
            1965 Population  9.935358e+06
                 GDP         1.006667e+09
            1966 Population  1.014884e+07
                 GDP         1.400000e+09
            1967 Population  1.036860e+07
                 GDP         1.673333e+09
            1968 Population  1.059979e+07
                 GDP         1.373333e+09
            1969 Population  1.084951e+07
                 GDP         1.408889e+09
            1970 Population  1.112110e+07
                 GDP         1.748887e+09
            1971 Population  1.141282e+07
                 GDP         1.831109e+09
            1972 Population  1.171690e+07
                 GDP         1.595555e+09
            1973 Population  1.202251e+07
                 GDP         1.733333e+09
            1974 Population  1.231555e+07
                 GDP         2.155555e+09
...                                   ...
Zimbabwe    2001 Population  1.260399e+07
                 GDP         6.777385e+09
            2002 Population  1.269143e+07
                 GDP         6.342116e+09
            2003 Population  1.277416e+07
                 GDP         5.727592e+09
            2004 Population  1.286783e+07
                 GDP         5.805598e+09
            2005 Population  1.298442e+07
                 GDP         5.755215e+09
            2006 Population  1.312794e+07
                 GDP         5.443896e+09
            2007 Population  1.329780e+07
                 GDP         5.291950e+09
            2008 Population  1.349546e+07
                 GDP         4.415703e+09
            2009 Population  1.372100e+07
                 GDP         8.157077e+09
            2010 Population  1.397390e+07
                 GDP         9.422161e+09
            2011 Population  1.425559e+07
                 GDP         1.095623e+10
            2012 Population  1.456548e+07
                 GDP         1.239272e+10
            2013 Population  1.489809e+07
                 GDP         1.349023e+10
            2014 Population  1.524586e+07
                 GDP         1.419691e+10
            2015 Population  1.560275e+07
                 GDP         1.389294e+10

[22422 rows x 1 columns]

In [127]:
ws.stack().unstack()

                  Population           GDP
country     year
Afghanistan 1960   8994793.0  5.377778e+08
            1961   9164945.0  5.488889e+08
            1962   9343772.0  5.466667e+08
            1963   9531555.0  7.511112e+08
            1964   9728645.0  8.000000e+08
            1965   9935358.0  1.006667e+09
            1966  10148841.0  1.400000e+09
            1967  10368600.0  1.673333e+09
            1968  10599790.0  1.373333e+09
            1969  10849510.0  1.408889e+09
            1970  11121097.0  1.748887e+09
            1971  11412821.0  1.831109e+09
            1972  11716896.0  1.595555e+09
            1973  12022514.0  1.733333e+09
            1974  12315553.0  2.155555e+09
            1975  12582954.0  2.366667e+09
            1976  12831361.0  2.555556e+09
            1977  13056499.0  2.953333e+09
            1978  13222547.0  3.300000e+09
            1979  13283279.0  3.697940e+09
            1980  13211412.0  3.641723e+09
            1981  12996923.0  3.478788e+09
            2001  20531160.0  2.461666e+09
            2002  21487079.0  4.128818e+09
            2003  22507368.0  4.583649e+09
            2004  23499850.0  5.285462e+09
            2005  24399948.0  6.275076e+09
            2006  25183615.0  7.057598e+09
            2007  25877544.0  9.843842e+09
            2008  26528741.0  1.019053e+10
...                      ...           ...
Zimbabwe    1986   9198874.0  6.217524e+09
            1987   9535657.0  6.741215e+09
            1988   9866776.0  7.814784e+09
            1989  10184966.0  8.286323e+09
            1990  10484771.0  8.783817e+09
            1991  10763036.0  8.641482e+09
            1992  11019717.0  6.751472e+09
            1993  11256512.0  6.563813e+09
            1994  11476807.0  6.890675e+09
            1995  11683136.0  7.111271e+09
            1996  11877664.0  8.553147e+09
            1997  12059858.0  8.529572e+09
            1998  12226742.0  6.401968e+09
            1999  12374019.0  6.858013e+09
            2000  12499981.0  6.689958e+09
            2001  12603988.0  6.777385e+09
            2002  12691431.0  6.342116e+09
            2003  12774162.0  5.727592e+09
            2004  12867828.0  5.805598e+09
            2005  12984418.0  5.755215e+09
            2006  13127942.0  5.443896e+09
            2007  13297798.0  5.291950e+09
            2008  13495462.0  4.415703e+09
            2009  13720997.0  8.157077e+09
            2010  13973897.0  9.422161e+09
            2011  14255592.0  1.095623e+10
            2012  14565482.0  1.239272e+10
            2013  14898092.0  1.349023e+10
            2014  15245855.0  1.419691e+10
            2015  15602751.0  1.389294e+10

[11211 rows x 2 columns]

In [134]:
 ws.unstack().head(3)

             Population                                                  \
year               1960        1961        1962        1963        1964
country
Afghanistan   8994793.0   9164945.0   9343772.0   9531555.0   9728645.0
Albania             NaN         NaN         NaN         NaN         NaN
Algeria      11124892.0  11404859.0  11690152.0  11985130.0  12295973.0

                                                                         \
year               1965        1966        1967        1968        1969
country
Afghanistan   9935358.0  10148841.0  10368600.0  10599790.0  10849510.0
Albania             NaN         NaN         NaN         NaN         NaN
Algeria      12626953.0  12980269.0  13354197.0  13744383.0  14144437.0

                 ...                GDP                              \
year             ...               2006          2007          2008
country          ...
Afghanistan      ...       7.057598e+09  9.843842e+09  1.019053e+10
Albania          ...       8.992642e+09  1.070101e+10  1.288135e+10
Algeria          ...       1.170273e+11  1.349771e+11  1.710007e+11

                                                                     \
year                 2009          2010          2011          2012
country
Afghanistan  1.248694e+10  1.593680e+10  1.793024e+10  2.053654e+10
Albania      1.204421e+10  1.192695e+10  1.289087e+10  1.231978e+10
Algeria      1.372110e+11  1.612073e+11  2.000131e+11  2.090474e+11


year                 2013          2014          2015
country
Afghanistan  2.004633e+10  2.005019e+10  1.919944e+10
Albania      1.278103e+10  1.327796e+10  1.145560e+10
Algeria      2.097035e+11  2.135185e+11  1.668386e+11

[3 rows x 112 columns]

In [135]:
s=ws.stack()

In [136]:
s.head(3)

country      year
Afghanistan  1960  Population    8.994793e+06
                   GDP           5.377778e+08
             1961  Population    9.164945e+06
dtype: float64

In [141]:
s.unstack(0)

country           Afghanistan       Albania       Algeria       Andorra  \
year
1960 Population  8.994793e+06           NaN  1.112489e+07           NaN
     GDP         5.377778e+08           NaN  2.723638e+09           NaN
1961 Population  9.164945e+06           NaN  1.140486e+07           NaN
     GDP         5.488889e+08           NaN  2.434767e+09           NaN
1962 Population  9.343772e+06           NaN  1.169015e+07           NaN
     GDP         5.466667e+08           NaN  2.001461e+09           NaN
1963 Population  9.531555e+06           NaN  1.198513e+07           NaN
     GDP         7.511112e+08           NaN  2.703004e+09           NaN
1964 Population  9.728645e+06           NaN  1.229597e+07           NaN
     GDP         8.000000e+08           NaN  2.909340e+09           NaN
1965 Population  9.935358e+06           NaN  1.262695e+07           NaN
     GDP         1.006667e+09           NaN  3.136284e+09           NaN
1966 Population  1.014884e+07           NaN  1.298027e+07           NaN
     GDP         1.400000e+09           NaN  3.039859e+09           NaN
1967 Population  1.036860e+07           NaN  1.335420e+07           NaN
     GDP         1.673333e+09           NaN  3.370870e+09           NaN
1968 Population  1.059979e+07           NaN  1.374438e+07           NaN
     GDP         1.373333e+09           NaN  3.852147e+09           NaN
1969 Population  1.084951e+07           NaN  1.414444e+07           NaN
     GDP         1.408889e+09           NaN  4.257253e+09           NaN
1970 Population  1.112110e+07           NaN  1.455003e+07  2.427900e+04
     GDP         1.748887e+09           NaN  4.863488e+09  7.861762e+07
1971 Population  1.141282e+07           NaN  1.496011e+07  2.556000e+04
     GDP         1.831109e+09           NaN  5.077222e+09  8.940659e+07
1972 Population  1.171690e+07           NaN  1.537710e+07  2.689200e+04
     GDP         1.595555e+09           NaN  6.761786e+09  1.134144e+08
1973 Population  1.202251e+07           NaN  1.580443e+07  2.823100e+04
     GDP         1.733333e+09           NaN  8.715106e+09  1.508416e+08
1974 Population  1.231555e+07           NaN  1.624711e+07  2.951400e+04
     GDP         2.155555e+09           NaN  1.320971e+10  1.865572e+08
...                       ...           ...           ...           ...
2001 Population  2.053116e+07  3.060173e+06  3.159032e+07  6.777000e+04
     GDP         2.461666e+09  4.060759e+09  5.474471e+10  1.484005e+09
2002 Population  2.148708e+07  3.051010e+06  3.199039e+07  7.104600e+04
     GDP         4.128818e+09  4.435079e+09  5.676029e+10  1.717564e+09
2003 Population  2.250737e+07  3.039616e+06  3.239489e+07  7.478300e+04
     GDP         4.583649e+09  5.746946e+09  6.786383e+10  2.373836e+09
2004 Population  2.349985e+07  3.026939e+06  3.281722e+07  7.833700e+04
     GDP         5.285462e+09  7.314865e+09  8.532500e+10  2.916913e+09
2005 Population  2.439995e+07  3.011487e+06  3.326789e+07  8.122300e+04
     GDP         6.275076e+09  8.158549e+09  1.031982e+11  3.248135e+09
2006 Population  2.518362e+07  2.992547e+06  3.374933e+07  8.337300e+04
     GDP         7.057598e+09  8.992642e+09  1.170273e+11  3.536452e+09
2007 Population  2.587754e+07  2.970017e+06  3.426197e+07  8.487800e+04
     GDP         9.843842e+09  1.070101e+10  1.349771e+11  4.010785e+09
2008 Population  2.652874e+07  2.947314e+06  3.481106e+07  8.561600e+04
     GDP         1.019053e+10  1.288135e+10  1.710007e+11  4.001349e+09
2009 Population  2.720729e+07  2.927519e+06  3.540179e+07  8.547400e+04
     GDP         1.248694e+10  1.204421e+10  1.372110e+11  3.649863e+09
2010 Population  2.796221e+07  2.913021e+06  3.603616e+07  8.441900e+04
     GDP         1.593680e+10  1.192695e+10  1.612073e+11  3.346317e+09
2011 Population  2.880917e+07  2.904780e+06  3.671713e+07  8.232600e+04
     GDP         1.793024e+10  1.289087e+10  2.000131e+11  3.427236e+09
2012 Population  2.972680e+07  2.900247e+06  3.743943e+07  7.931600e+04
     GDP         2.053654e+10  1.231978e+10  2.090474e+11  3.146178e+09
2013 Population  3.068250e+07  2.896652e+06  3.818614e+07  7.590200e+04
     GDP         2.004633e+10  1.278103e+10  2.097035e+11  3.249101e+09
2014 Population  3.162751e+07  2.893654e+06  3.893433e+07           NaN
     GDP         2.005019e+10  1.327796e+10  2.135185e+11           NaN
2015 Population  3.252656e+07  2.889167e+06  3.966652e+07           NaN
     GDP         1.919944e+10  1.145560e+10  1.668386e+11           NaN

country                Angola  Antigua and Barbuda    Arab World  \
year
1960 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1961 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1962 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1963 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1964 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1965 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1966 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1967 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1968 Population           NaN                  NaN  1.155571e+08
     GDP                  NaN                  NaN  2.552596e+10
1969 Population           NaN                  NaN  1.188239e+08
     GDP                  NaN                  NaN  2.817577e+10
1970 Population           NaN                  NaN  1.221282e+08
     GDP                  NaN                  NaN  3.109149e+10
1971 Population           NaN                  NaN  1.254391e+08
     GDP                  NaN                  NaN  3.610721e+10
1972 Population           NaN                  NaN  1.288012e+08
     GDP                  NaN                  NaN  4.296931e+10
1973 Population           NaN                  NaN  1.322990e+08
     GDP                  NaN                  NaN  5.459015e+10
1974 Population           NaN                  NaN  1.360445e+08
     GDP                  NaN                  NaN  1.046016e+11
...                       ...                  ...           ...
2001 Population  1.556279e+07         7.897200e+04  2.872918e+08
     GDP         8.936064e+09         7.737652e+08  7.221506e+11
2002 Population  1.610970e+07         8.003000e+04  2.934026e+08
     GDP         1.249735e+10         8.025293e+08  7.279939e+11
2003 Population  1.669140e+07         8.090400e+04  2.997320e+08
     GDP         1.418895e+10         8.399964e+08  8.218702e+11
2004 Population  1.729550e+07         8.171800e+04  3.063874e+08
     GDP         1.964085e+10         8.983561e+08  9.639180e+11
2005 Population  1.791294e+07         8.256500e+04  3.134309e+08
     GDP         2.823371e+10         9.973741e+08  1.184735e+12
2006 Population  1.854147e+07         8.346700e+04  3.209067e+08
     GDP         4.178948e+10         1.135144e+09  1.404190e+12
2007 Population  1.918391e+07         8.439700e+04  3.287666e+08
     GDP         6.044892e+10         1.289254e+09  1.641666e+12
2008 Population  1.984225e+07         8.535000e+04  3.368865e+08
     GDP         8.417803e+10         1.347350e+09  2.081343e+12
2009 Population  2.052010e+07         8.630000e+04  3.450542e+08
     GDP         7.549238e+10         1.206410e+09  1.798878e+12
2010 Population  2.121995e+07         8.723300e+04  3.531122e+08
     GDP         8.247091e+10         1.135539e+09  2.103825e+12
2011 Population  2.194230e+07         8.815200e+04  3.610318e+08
     GDP         1.041159e+11         1.129918e+09  2.497945e+12
2012 Population  2.268563e+07         8.906900e+04  3.688026e+08
     GDP         1.153984e+11         1.204713e+09  2.773270e+12
2013 Population  2.344820e+07         8.998500e+04  3.765043e+08
     GDP         1.249121e+11         1.200588e+09  2.846994e+12
2014 Population  2.422752e+07         9.090000e+04  3.842226e+08
     GDP         1.267751e+11         1.220976e+09  2.873600e+12
2015 Population  2.502197e+07         9.181800e+04  3.920223e+08
     GDP         1.026431e+11         1.297285e+09  2.530102e+12

country             Argentina       Armenia         Aruba      ...       \
year                                                           ...
1960 Population           NaN           NaN           NaN      ...
     GDP                  NaN           NaN           NaN      ...
1961 Population           NaN           NaN           NaN      ...
     GDP                  NaN           NaN           NaN      ...
1962 Population  2.128768e+07           NaN           NaN      ...
     GDP         2.445060e+10           NaN           NaN      ...
1963 Population  2.162184e+07           NaN           NaN      ...
     GDP         1.827212e+10           NaN           NaN      ...
1964 Population  2.195393e+07           NaN           NaN      ...
     GDP         2.560525e+10           NaN           NaN      ...
1965 Population  2.228339e+07           NaN           NaN      ...
     GDP         2.834471e+10           NaN           NaN      ...
1966 Population  2.260875e+07           NaN           NaN      ...
     GDP         2.863047e+10           NaN           NaN      ...
1967 Population  2.293220e+07           NaN           NaN      ...
     GDP         2.425667e+10           NaN           NaN      ...
1968 Population  2.326127e+07           NaN           NaN      ...
     GDP         2.643686e+10           NaN           NaN      ...
1969 Population  2.360599e+07           NaN           NaN      ...
     GDP         3.125628e+10           NaN           NaN      ...
1970 Population  2.397306e+07           NaN           NaN      ...
     GDP         3.158421e+10           NaN           NaN      ...
1971 Population  2.436644e+07           NaN           NaN      ...
     GDP         3.329320e+10           NaN           NaN      ...
1972 Population  2.478295e+07           NaN           NaN      ...
     GDP         3.473300e+10           NaN           NaN      ...
1973 Population  2.521339e+07           NaN           NaN      ...
     GDP         5.254400e+10           NaN           NaN      ...
1974 Population  2.564450e+07           NaN           NaN      ...
     GDP         7.243678e+10           NaN           NaN      ...
...                       ...           ...           ...      ...
2001 Population  3.747154e+07  3.060036e+06  9.289400e+04      ...
     GDP         2.686968e+11  2.118468e+09  1.920263e+09      ...
2002 Population  3.788944e+07  3.047249e+06  9.499500e+04      ...
     GDP         9.772451e+10  2.376335e+09  1.941095e+09      ...
2003 Population  3.830948e+07  3.036420e+06  9.701500e+04      ...
     GDP         1.275863e+11  2.807061e+09  2.021302e+09      ...
2004 Population  3.872878e+07  3.025982e+06  9.874200e+04      ...
     GDP         1.818731e+11  3.576615e+09  2.228279e+09      ...
2005 Population  3.914549e+07  3.014917e+06  1.000310e+05      ...
     GDP         2.208138e+11  4.900470e+09  2.331006e+09      ...
2006 Population  3.955875e+07  3.002161e+06  1.008300e+05      ...
     GDP         2.626665e+11  6.384452e+09  2.421475e+09      ...
2007 Population  3.996990e+07  2.988117e+06  1.012180e+05      ...
     GDP         3.293175e+11  9.206302e+09  2.623726e+09      ...
2008 Population  4.038186e+07  2.975029e+06  1.013420e+05      ...
     GDP         4.037820e+11  1.166204e+10  2.791961e+09      ...
2009 Population  4.079864e+07  2.966108e+06  1.014160e+05      ...
     GDP         3.766279e+11  8.647937e+09  2.498933e+09      ...
2010 Population  4.122288e+07  2.963496e+06  1.015970e+05      ...
     GDP         4.616402e+11  9.260285e+09  2.467704e+09      ...
2011 Population  4.165562e+07  2.967984e+06  1.019360e+05      ...
     GDP         5.578902e+11  1.014211e+10  2.584464e+09      ...
2012 Population  4.209522e+07  2.978339e+06           NaN      ...
     GDP         6.043785e+11  1.061932e+10           NaN      ...
2013 Population  4.253830e+07  2.992192e+06           NaN      ...
     GDP         6.239320e+11  1.112147e+10           NaN      ...
2014 Population  4.298003e+07  3.006154e+06           NaN      ...
     GDP         5.480549e+11  1.164444e+10           NaN      ...
2015 Population           NaN  3.017712e+06           NaN      ...
     GDP                  NaN  1.056140e+10           NaN      ...

country            Uzbekistan       Vanuatu  Venezuela, RB       Vietnam  \
year
1960 Population           NaN           NaN   8.146845e+06           NaN
     GDP                  NaN           NaN   8.607600e+09           NaN
1961 Population           NaN           NaN   8.461684e+06           NaN
     GDP                  NaN           NaN   8.923367e+09           NaN
1962 Population           NaN           NaN   8.790590e+06           NaN
     GDP                  NaN           NaN   9.873398e+09           NaN
1963 Population           NaN           NaN   9.130346e+06           NaN
     GDP                  NaN           NaN   1.066338e+10           NaN
1964 Population           NaN           NaN   9.476255e+06           NaN
     GDP                  NaN           NaN   9.113581e+09           NaN
1965 Population           NaN           NaN   9.824694e+06           NaN
     GDP                  NaN           NaN   9.602945e+09           NaN
1966 Population           NaN           NaN   1.017514e+07           NaN
     GDP                  NaN           NaN   1.009657e+10           NaN
1967 Population           NaN           NaN   1.052805e+07           NaN
     GDP                  NaN           NaN   1.047278e+10           NaN
1968 Population           NaN           NaN   1.088200e+07           NaN
     GDP                  NaN           NaN   1.147091e+10           NaN
1969 Population           NaN           NaN   1.123549e+07           NaN
     GDP                  NaN           NaN   1.192757e+10           NaN
1970 Population           NaN           NaN   1.158776e+07           NaN
     GDP                  NaN           NaN   1.299312e+10           NaN
1971 Population           NaN           NaN   1.193780e+07           NaN
     GDP                  NaN           NaN   1.447156e+10           NaN
1972 Population           NaN           NaN   1.228643e+07           NaN
     GDP                  NaN           NaN   1.592287e+10           NaN
1973 Population           NaN           NaN   1.263697e+07           NaN
     GDP                  NaN           NaN   1.944593e+10           NaN
1974 Population           NaN           NaN   1.299402e+07           NaN
     GDP                  NaN           NaN   2.908710e+10           NaN
...                       ...           ...            ...           ...
2001 Population  2.496445e+07  1.892880e+05   2.494022e+07  7.862050e+07
     GDP         1.140135e+10  2.579269e+08   1.229097e+11  3.529135e+10
2002 Population  2.527185e+07  1.939570e+05   2.539914e+07  7.953770e+07
     GDP         9.687951e+09  2.626038e+08   9.288959e+10  3.794790e+10
2003 Population  2.556765e+07  1.989630e+05   2.585755e+07  8.046740e+07
     GDP         1.012811e+10  3.144631e+08   8.362219e+10  4.271707e+10
2004 Population  2.586435e+07  2.041440e+05   2.631448e+07  8.143640e+07
     GDP         1.203002e+10  3.649969e+08   1.124514e+11  4.942411e+10
2005 Population  2.616700e+07  2.093750e+05   2.676912e+07  8.239210e+07
     GDP         1.430751e+10  3.949626e+08   1.455135e+11  5.763326e+10
2006 Population  2.648825e+07  2.146350e+05   2.722123e+07  8.331120e+07
     GDP         1.703090e+10  4.393768e+08   1.834775e+11  6.637166e+10
2007 Population  2.686800e+07  2.199560e+05   2.767066e+07  8.421850e+07
     GDP         2.231139e+10  5.264283e+08   2.303642e+11  7.741443e+10
2008 Population  2.730280e+07  2.253350e+05   2.811672e+07  8.511870e+07
     GDP         2.793403e+10  6.079586e+08   3.156002e+11  9.913030e+10
2009 Population  2.776740e+07  2.307820e+05   2.855861e+07  8.602500e+07
     GDP         3.281683e+10  6.100666e+08   3.294190e+11  1.060146e+11
2010 Population  2.856240e+07  2.362990e+05   2.899574e+07  8.693250e+07
     GDP         3.933277e+10  7.008043e+08   3.938015e+11  1.159317e+11
2011 Population  2.933940e+07  2.418760e+05   2.942763e+07  8.786030e+07
     GDP         4.532432e+10  7.921497e+08   3.164822e+11  1.355395e+11
2012 Population  2.977450e+07  2.474980e+05   2.985424e+07  8.880920e+07
     GDP         5.118344e+10  7.817029e+08   3.812862e+11  1.558200e+11
2013 Population  3.024320e+07  2.531650e+05   3.027604e+07  8.975950e+07
     GDP         5.679566e+10  8.017876e+08   3.713366e+11  1.712220e+11
2014 Population  3.075770e+07  2.588830e+05            NaN  9.072890e+07
     GDP         6.313285e+10  8.149546e+08            NaN  1.862047e+11
2015 Population  3.129950e+07           NaN            NaN  9.170380e+07
     GDP         6.673280e+10           NaN            NaN  1.935994e+11

country          Virgin Islands (U.S.)  West Bank and Gaza         World  \
year
1960 Population                32000.0                 NaN  3.035056e+09
     GDP                    24200000.0                 NaN  1.364643e+12
1961 Population                34100.0                 NaN  3.076121e+09
     GDP                    25700000.0                 NaN  1.420440e+12
1962 Population                36300.0                 NaN  3.129064e+09
     GDP                    36900000.0                 NaN  1.524573e+12
1963 Population                38700.0                 NaN  3.193947e+09
     GDP                    41400000.0                 NaN  1.638187e+12
1964 Population                41300.0                 NaN  3.259355e+09
     GDP                    53800000.0                 NaN  1.799675e+12
1965 Population                44000.0                 NaN  3.326054e+09
     GDP                    66500000.0                 NaN  1.959900e+12
1966 Population                47300.0                 NaN  3.395866e+09
     GDP                    84100000.0                 NaN  2.125397e+12
1967 Population                50800.0                 NaN  3.465297e+09
     GDP                   115400000.0                 NaN  2.262923e+12
1968 Population                54600.0                 NaN  3.535512e+09
     GDP                   173800000.0                 NaN  2.440549e+12
1969 Population                58600.0                 NaN  3.609910e+09
     GDP                   211300000.0                 NaN  2.686747e+12
1970 Population                63000.0                 NaN  3.684997e+09
     GDP                   219000000.0                 NaN  2.950656e+12
1971 Population                71000.0                 NaN  3.762290e+09
     GDP                   257000000.0                 NaN  3.259057e+12
1972 Population                76000.0                 NaN  3.839016e+09
     GDP                   307100000.0                 NaN  3.757853e+12
1973 Population                84000.0                 NaN  3.914800e+09
     GDP                   351600000.0                 NaN  4.578523e+12
1974 Population                90000.0                 NaN  3.991194e+09
     GDP                   395400000.0                 NaN  5.279355e+12
...                                ...                 ...           ...
2001 Population                    NaN        2.997784e+06  6.195590e+09
     GDP                           NaN        4.003700e+09  3.313421e+13
2002 Population                    NaN        3.075373e+06  6.274734e+09
     GDP                           NaN        3.555800e+09  3.441805e+13
2003 Population                    NaN        3.154969e+06  6.353976e+09

In [142]:
s.unstack("country")

country           Afghanistan       Albania       Algeria       Andorra  \
year
1960 Population  8.994793e+06           NaN  1.112489e+07           NaN
     GDP         5.377778e+08           NaN  2.723638e+09           NaN
1961 Population  9.164945e+06           NaN  1.140486e+07           NaN
     GDP         5.488889e+08           NaN  2.434767e+09           NaN
1962 Population  9.343772e+06           NaN  1.169015e+07           NaN
     GDP         5.466667e+08           NaN  2.001461e+09           NaN
1963 Population  9.531555e+06           NaN  1.198513e+07           NaN
     GDP         7.511112e+08           NaN  2.703004e+09           NaN
1964 Population  9.728645e+06           NaN  1.229597e+07           NaN
     GDP         8.000000e+08           NaN  2.909340e+09           NaN
1965 Population  9.935358e+06           NaN  1.262695e+07           NaN
     GDP         1.006667e+09           NaN  3.136284e+09           NaN
1966 Population  1.014884e+07           NaN  1.298027e+07           NaN
     GDP         1.400000e+09           NaN  3.039859e+09           NaN
1967 Population  1.036860e+07           NaN  1.335420e+07           NaN
     GDP         1.673333e+09           NaN  3.370870e+09           NaN
1968 Population  1.059979e+07           NaN  1.374438e+07           NaN
     GDP         1.373333e+09           NaN  3.852147e+09           NaN
1969 Population  1.084951e+07           NaN  1.414444e+07           NaN
     GDP         1.408889e+09           NaN  4.257253e+09           NaN
1970 Population  1.112110e+07           NaN  1.455003e+07  2.427900e+04
     GDP         1.748887e+09           NaN  4.863488e+09  7.861762e+07
1971 Population  1.141282e+07           NaN  1.496011e+07  2.556000e+04
     GDP         1.831109e+09           NaN  5.077222e+09  8.940659e+07
1972 Population  1.171690e+07           NaN  1.537710e+07  2.689200e+04
     GDP         1.595555e+09           NaN  6.761786e+09  1.134144e+08
1973 Population  1.202251e+07           NaN  1.580443e+07  2.823100e+04
     GDP         1.733333e+09           NaN  8.715106e+09  1.508416e+08
1974 Population  1.231555e+07           NaN  1.624711e+07  2.951400e+04
     GDP         2.155555e+09           NaN  1.320971e+10  1.865572e+08
...                       ...           ...           ...           ...
2001 Population  2.053116e+07  3.060173e+06  3.159032e+07  6.777000e+04
     GDP         2.461666e+09  4.060759e+09  5.474471e+10  1.484005e+09
2002 Population  2.148708e+07  3.051010e+06  3.199039e+07  7.104600e+04
     GDP         4.128818e+09  4.435079e+09  5.676029e+10  1.717564e+09
2003 Population  2.250737e+07  3.039616e+06  3.239489e+07  7.478300e+04
     GDP         4.583649e+09  5.746946e+09  6.786383e+10  2.373836e+09
2004 Population  2.349985e+07  3.026939e+06  3.281722e+07  7.833700e+04
     GDP         5.285462e+09  7.314865e+09  8.532500e+10  2.916913e+09
2005 Population  2.439995e+07  3.011487e+06  3.326789e+07  8.122300e+04
     GDP         6.275076e+09  8.158549e+09  1.031982e+11  3.248135e+09
2006 Population  2.518362e+07  2.992547e+06  3.374933e+07  8.337300e+04
     GDP         7.057598e+09  8.992642e+09  1.170273e+11  3.536452e+09
2007 Population  2.587754e+07  2.970017e+06  3.426197e+07  8.487800e+04
     GDP         9.843842e+09  1.070101e+10  1.349771e+11  4.010785e+09
2008 Population  2.652874e+07  2.947314e+06  3.481106e+07  8.561600e+04
     GDP         1.019053e+10  1.288135e+10  1.710007e+11  4.001349e+09
2009 Population  2.720729e+07  2.927519e+06  3.540179e+07  8.547400e+04
     GDP         1.248694e+10  1.204421e+10  1.372110e+11  3.649863e+09
2010 Population  2.796221e+07  2.913021e+06  3.603616e+07  8.441900e+04
     GDP         1.593680e+10  1.192695e+10  1.612073e+11  3.346317e+09
2011 Population  2.880917e+07  2.904780e+06  3.671713e+07  8.232600e+04
     GDP         1.793024e+10  1.289087e+10  2.000131e+11  3.427236e+09
2012 Population  2.972680e+07  2.900247e+06  3.743943e+07  7.931600e+04
     GDP         2.053654e+10  1.231978e+10  2.090474e+11  3.146178e+09
2013 Population  3.068250e+07  2.896652e+06  3.818614e+07  7.590200e+04
     GDP         2.004633e+10  1.278103e+10  2.097035e+11  3.249101e+09
2014 Population  3.162751e+07  2.893654e+06  3.893433e+07           NaN
     GDP         2.005019e+10  1.327796e+10  2.135185e+11           NaN
2015 Population  3.252656e+07  2.889167e+06  3.966652e+07           NaN
     GDP         1.919944e+10  1.145560e+10  1.668386e+11           NaN

country                Angola  Antigua and Barbuda    Arab World  \
year
1960 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1961 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1962 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1963 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1964 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1965 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1966 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1967 Population           NaN                  NaN           NaN
     GDP                  NaN                  NaN           NaN
1968 Population           NaN                  NaN  1.155571e+08
     GDP                  NaN                  NaN  2.552596e+10
1969 Population           NaN                  NaN  1.188239e+08
     GDP                  NaN                  NaN  2.817577e+10
1970 Population           NaN                  NaN  1.221282e+08
     GDP                  NaN                  NaN  3.109149e+10
1971 Population           NaN                  NaN  1.254391e+08
     GDP                  NaN                  NaN  3.610721e+10
1972 Population           NaN                  NaN  1.288012e+08
     GDP                  NaN                  NaN  4.296931e+10
1973 Population           NaN                  NaN  1.322990e+08
     GDP                  NaN                  NaN  5.459015e+10
1974 Population           NaN                  NaN  1.360445e+08
     GDP                  NaN                  NaN  1.046016e+11
...                       ...                  ...           ...
2001 Population  1.556279e+07         7.897200e+04  2.872918e+08
     GDP         8.936064e+09         7.737652e+08  7.221506e+11
2002 Population  1.610970e+07         8.003000e+04  2.934026e+08
     GDP         1.249735e+10         8.025293e+08  7.279939e+11
2003 Population  1.669140e+07         8.090400e+04  2.997320e+08
     GDP         1.418895e+10         8.399964e+08  8.218702e+11
2004 Population  1.729550e+07         8.171800e+04  3.063874e+08
     GDP         1.964085e+10         8.983561e+08  9.639180e+11
2005 Population  1.791294e+07         8.256500e+04  3.134309e+08
     GDP         2.823371e+10         9.973741e+08  1.184735e+12
2006 Population  1.854147e+07         8.346700e+04  3.209067e+08
     GDP         4.178948e+10         1.135144e+09  1.404190e+12
2007 Population  1.918391e+07         8.439700e+04  3.287666e+08
     GDP         6.044892e+10         1.289254e+09  1.641666e+12
2008 Population  1.984225e+07         8.535000e+04  3.368865e+08
     GDP         8.417803e+10         1.347350e+09  2.081343e+12
2009 Population  2.052010e+07         8.630000e+04  3.450542e+08
     GDP         7.549238e+10         1.206410e+09  1.798878e+12
2010 Population  2.121995e+07         8.723300e+04  3.531122e+08
     GDP         8.247091e+10         1.135539e+09  2.103825e+12
2011 Population  2.194230e+07         8.815200e+04  3.610318e+08
     GDP         1.041159e+11         1.129918e+09  2.497945e+12
2012 Population  2.268563e+07         8.906900e+04  3.688026e+08
     GDP         1.153984e+11         1.204713e+09  2.773270e+12
2013 Population  2.344820e+07         8.998500e+04  3.765043e+08
     GDP         1.249121e+11         1.200588e+09  2.846994e+12
2014 Population  2.422752e+07         9.090000e+04  3.842226e+08
     GDP         1.267751e+11         1.220976e+09  2.873600e+12
2015 Population  2.502197e+07         9.181800e+04  3.920223e+08
     GDP         1.026431e+11         1.297285e+09  2.530102e+12

country             Argentina       Armenia         Aruba      ...       \
year                                                           ...
1960 Population           NaN           NaN           NaN      ...
     GDP                  NaN           NaN           NaN      ...
1961 Population           NaN           NaN           NaN      ...
     GDP                  NaN           NaN           NaN      ...
1962 Population  2.128768e+07           NaN           NaN      ...
     GDP         2.445060e+10           NaN           NaN      ...
1963 Population  2.162184e+07           NaN           NaN      ...
     GDP         1.827212e+10           NaN           NaN      ...
1964 Population  2.195393e+07           NaN           NaN      ...
     GDP         2.560525e+10           NaN           NaN      ...
1965 Population  2.228339e+07           NaN           NaN      ...
     GDP         2.834471e+10           NaN           NaN      ...
1966 Population  2.260875e+07           NaN           NaN      ...
     GDP         2.863047e+10           NaN           NaN      ...
1967 Population  2.293220e+07           NaN           NaN      ...
     GDP         2.425667e+10           NaN           NaN      ...
1968 Population  2.326127e+07           NaN           NaN      ...
     GDP         2.643686e+10           NaN           NaN      ...
1969 Population  2.360599e+07           NaN           NaN      ...
     GDP         3.125628e+10           NaN           NaN      ...
1970 Population  2.397306e+07           NaN           NaN      ...
     GDP         3.158421e+10           NaN           NaN      ...
1971 Population  2.436644e+07           NaN           NaN      ...
     GDP         3.329320e+10           NaN           NaN      ...
1972 Population  2.478295e+07           NaN           NaN      ...
     GDP         3.473300e+10           NaN           NaN      ...
1973 Population  2.521339e+07           NaN           NaN      ...
     GDP         5.254400e+10           NaN           NaN      ...
1974 Population  2.564450e+07           NaN           NaN      ...
     GDP         7.243678e+10           NaN           NaN      ...
...                       ...           ...           ...      ...
2001 Population  3.747154e+07  3.060036e+06  9.289400e+04      ...
     GDP         2.686968e+11  2.118468e+09  1.920263e+09      ...
2002 Population  3.788944e+07  3.047249e+06  9.499500e+04      ...
     GDP         9.772451e+10  2.376335e+09  1.941095e+09      ...
2003 Population  3.830948e+07  3.036420e+06  9.701500e+04      ...
     GDP         1.275863e+11  2.807061e+09  2.021302e+09      ...
2004 Population  3.872878e+07  3.025982e+06  9.874200e+04      ...
     GDP         1.818731e+11  3.576615e+09  2.228279e+09      ...
2005 Population  3.914549e+07  3.014917e+06  1.000310e+05      ...
     GDP         2.208138e+11  4.900470e+09  2.331006e+09      ...
2006 Population  3.955875e+07  3.002161e+06  1.008300e+05      ...
     GDP         2.626665e+11  6.384452e+09  2.421475e+09      ...
2007 Population  3.996990e+07  2.988117e+06  1.012180e+05      ...
     GDP         3.293175e+11  9.206302e+09  2.623726e+09      ...
2008 Population  4.038186e+07  2.975029e+06  1.013420e+05      ...
     GDP         4.037820e+11  1.166204e+10  2.791961e+09      ...
2009 Population  4.079864e+07  2.966108e+06  1.014160e+05      ...
     GDP         3.766279e+11  8.647937e+09  2.498933e+09      ...
2010 Population  4.122288e+07  2.963496e+06  1.015970e+05      ...
     GDP         4.616402e+11  9.260285e+09  2.467704e+09      ...
2011 Population  4.165562e+07  2.967984e+06  1.019360e+05      ...
     GDP         5.578902e+11  1.014211e+10  2.584464e+09      ...
2012 Population  4.209522e+07  2.978339e+06           NaN      ...
     GDP         6.043785e+11  1.061932e+10           NaN      ...
2013 Population  4.253830e+07  2.992192e+06           NaN      ...
     GDP         6.239320e+11  1.112147e+10           NaN      ...
2014 Population  4.298003e+07  3.006154e+06           NaN      ...
     GDP         5.480549e+11  1.164444e+10           NaN      ...
2015 Population           NaN  3.017712e+06           NaN      ...
     GDP                  NaN  1.056140e+10           NaN      ...

country            Uzbekistan       Vanuatu  Venezuela, RB       Vietnam  \
year
1960 Population           NaN           NaN   8.146845e+06           NaN
     GDP                  NaN           NaN   8.607600e+09           NaN
1961 Population           NaN           NaN   8.461684e+06           NaN
     GDP                  NaN           NaN   8.923367e+09           NaN
1962 Population           NaN           NaN   8.790590e+06           NaN
     GDP                  NaN           NaN   9.873398e+09           NaN
1963 Population           NaN           NaN   9.130346e+06           NaN
     GDP                  NaN           NaN   1.066338e+10           NaN
1964 Population           NaN           NaN   9.476255e+06           NaN
     GDP                  NaN           NaN   9.113581e+09           NaN
1965 Population           NaN           NaN   9.824694e+06           NaN
     GDP                  NaN           NaN   9.602945e+09           NaN
1966 Population           NaN           NaN   1.017514e+07           NaN
     GDP                  NaN           NaN   1.009657e+10           NaN
1967 Population           NaN           NaN   1.052805e+07           NaN
     GDP                  NaN           NaN   1.047278e+10           NaN
1968 Population           NaN           NaN   1.088200e+07           NaN
     GDP                  NaN           NaN   1.147091e+10           NaN
1969 Population           NaN           NaN   1.123549e+07           NaN
     GDP                  NaN           NaN   1.192757e+10           NaN
1970 Population           NaN           NaN   1.158776e+07           NaN
     GDP                  NaN           NaN   1.299312e+10           NaN
1971 Population           NaN           NaN   1.193780e+07           NaN
     GDP                  NaN           NaN   1.447156e+10           NaN
1972 Population           NaN           NaN   1.228643e+07           NaN
     GDP                  NaN           NaN   1.592287e+10           NaN
1973 Population           NaN           NaN   1.263697e+07           NaN
     GDP                  NaN           NaN   1.944593e+10           NaN
1974 Population           NaN           NaN   1.299402e+07           NaN
     GDP                  NaN           NaN   2.908710e+10           NaN
...                       ...           ...            ...           ...
2001 Population  2.496445e+07  1.892880e+05   2.494022e+07  7.862050e+07
     GDP         1.140135e+10  2.579269e+08   1.229097e+11  3.529135e+10
2002 Population  2.527185e+07  1.939570e+05   2.539914e+07  7.953770e+07
     GDP         9.687951e+09  2.626038e+08   9.288959e+10  3.794790e+10
2003 Population  2.556765e+07  1.989630e+05   2.585755e+07  8.046740e+07
     GDP         1.012811e+10  3.144631e+08   8.362219e+10  4.271707e+10
2004 Population  2.586435e+07  2.041440e+05   2.631448e+07  8.143640e+07
     GDP         1.203002e+10  3.649969e+08   1.124514e+11  4.942411e+10
2005 Population  2.616700e+07  2.093750e+05   2.676912e+07  8.239210e+07
     GDP         1.430751e+10  3.949626e+08   1.455135e+11  5.763326e+10
2006 Population  2.648825e+07  2.146350e+05   2.722123e+07  8.331120e+07
     GDP         1.703090e+10  4.393768e+08   1.834775e+11  6.637166e+10
2007 Population  2.686800e+07  2.199560e+05   2.767066e+07  8.421850e+07
     GDP         2.231139e+10  5.264283e+08   2.303642e+11  7.741443e+10
2008 Population  2.730280e+07  2.253350e+05   2.811672e+07  8.511870e+07
     GDP         2.793403e+10  6.079586e+08   3.156002e+11  9.913030e+10
2009 Population  2.776740e+07  2.307820e+05   2.855861e+07  8.602500e+07
     GDP         3.281683e+10  6.100666e+08   3.294190e+11  1.060146e+11
2010 Population  2.856240e+07  2.362990e+05   2.899574e+07  8.693250e+07
     GDP         3.933277e+10  7.008043e+08   3.938015e+11  1.159317e+11
2011 Population  2.933940e+07  2.418760e+05   2.942763e+07  8.786030e+07
     GDP         4.532432e+10  7.921497e+08   3.164822e+11  1.355395e+11
2012 Population  2.977450e+07  2.474980e+05   2.985424e+07  8.880920e+07
     GDP         5.118344e+10  7.817029e+08   3.812862e+11  1.558200e+11
2013 Population  3.024320e+07  2.531650e+05   3.027604e+07  8.975950e+07
     GDP         5.679566e+10  8.017876e+08   3.713366e+11  1.712220e+11
2014 Population  3.075770e+07  2.588830e+05            NaN  9.072890e+07
     GDP         6.313285e+10  8.149546e+08            NaN  1.862047e+11
2015 Population  3.129950e+07           NaN            NaN  9.170380e+07
     GDP         6.673280e+10           NaN            NaN  1.935994e+11

country          Virgin Islands (U.S.)  West Bank and Gaza         World  \
year
1960 Population                32000.0                 NaN  3.035056e+09
     GDP                    24200000.0                 NaN  1.364643e+12
1961 Population                34100.0                 NaN  3.076121e+09
     GDP                    25700000.0                 NaN  1.420440e+12
1962 Population                36300.0                 NaN  3.129064e+09
     GDP                    36900000.0                 NaN  1.524573e+12
1963 Population                38700.0                 NaN  3.193947e+09
     GDP                    41400000.0                 NaN  1.638187e+12
1964 Population                41300.0                 NaN  3.259355e+09
     GDP                    53800000.0                 NaN  1.799675e+12
1965 Population                44000.0                 NaN  3.326054e+09
     GDP                    66500000.0                 NaN  1.959900e+12
1966 Population                47300.0                 NaN  3.395866e+09
     GDP                    84100000.0                 NaN  2.125397e+12
1967 Population                50800.0                 NaN  3.465297e+09
     GDP                   115400000.0                 NaN  2.262923e+12
1968 Population                54600.0                 NaN  3.535512e+09
     GDP                   173800000.0                 NaN  2.440549e+12
1969 Population                58600.0                 NaN  3.609910e+09
     GDP                   211300000.0                 NaN  2.686747e+12
1970 Population                63000.0                 NaN  3.684997e+09
     GDP                   219000000.0                 NaN  2.950656e+12
1971 Population                71000.0                 NaN  3.762290e+09
     GDP                   257000000.0                 NaN  3.259057e+12
1972 Population                76000.0                 NaN  3.839016e+09
     GDP                   307100000.0                 NaN  3.757853e+12
1973 Population                84000.0                 NaN  3.914800e+09
     GDP                   351600000.0                 NaN  4.578523e+12
1974 Population                90000.0                 NaN  3.991194e+09
     GDP                   395400000.0                 NaN  5.279355e+12
...                                ...                 ...           ...
2001 Population                    NaN        2.997784e+06  6.195590e+09
     GDP                           NaN        4.003700e+09  3.313421e+13
2002 Population                    NaN        3.075373e+06  6.274734e+09
     GDP                           NaN        3.555800e+09  3.441805e+13
2003 Population                    NaN        3.154969e+06  6.353976e+09

In [147]:
s.unstack(level=["year"],fill_value=0)

year                                      1960          1961          1962  \
country
Afghanistan           Population  8.994793e+06  9.164945e+06  9.343772e+06
                      GDP         5.377778e+08  5.488889e+08  5.466667e+08
Albania               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria               Population  1.112489e+07  1.140486e+07  1.169015e+07
                      GDP         2.723638e+09  2.434767e+09  2.001461e+09
Andorra               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Angola                Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Antigua and Barbuda   Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Arab World            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Argentina             Population  0.000000e+00  0.000000e+00  2.128768e+07
                      GDP         0.000000e+00  0.000000e+00  2.445060e+10
Armenia               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Aruba                 Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Australia             Population  1.027648e+07  1.048300e+07  1.074200e+07
                      GDP         1.856759e+10  1.963938e+10  1.988353e+10
Austria               Population  7.047539e+06  7.086299e+06  7.129864e+06
                      GDP         6.592694e+09  7.311750e+09  7.756110e+09
Azerbaijan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Bahamas, The          Population  1.095260e+05  1.151080e+05  1.210830e+05
                      GDP         1.698023e+08  1.900962e+08  2.122528e+08
Bahrain               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
...                                        ...           ...           ...
United Arab Emirates  Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
United Kingdom        Population  5.240000e+07  5.280000e+07  5.325000e+07
                      GDP         7.232805e+10  7.669436e+10  8.060194e+10
United States         Population  1.806710e+08  1.836910e+08  1.865380e+08
                      GDP         5.433000e+11  5.633000e+11  6.051000e+11
Upper middle income   Population  1.154592e+09  1.159145e+09  1.176093e+09
                      GDP         1.854612e+11  1.690732e+11  1.777957e+11
Uruguay               Population  2.538651e+06  2.571691e+06  2.603887e+06
                      GDP         1.242289e+09  1.547389e+09  1.710004e+09
Uzbekistan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Vanuatu               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Venezuela, RB         Population  8.146845e+06  8.461684e+06  8.790590e+06
                      GDP         8.607600e+09  8.923367e+09  9.873398e+09
Vietnam               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Virgin Islands (U.S.) Population  3.200000e+04  3.410000e+04  3.630000e+04
                      GDP         2.420000e+07  2.570000e+07  3.690000e+07
West Bank and Gaza    Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
World                 Population  3.035056e+09  3.076121e+09  3.129064e+09
                      GDP         1.364643e+12  1.420440e+12  1.524573e+12
Yemen, Rep.           Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia                Population  3.049586e+06  3.142848e+06  3.240664e+06
                      GDP         6.987397e+08  6.823597e+08  6.792797e+08
Zimbabwe              Population  3.752390e+06  3.876638e+06  4.006262e+06
                      GDP         1.052990e+09  1.096647e+09  1.117602e+09

year                                      1963          1964          1965  \
country
Afghanistan           Population  9.531555e+06  9.728645e+06  9.935358e+06
                      GDP         7.511112e+08  8.000000e+08  1.006667e+09
Albania               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria               Population  1.198513e+07  1.229597e+07  1.262695e+07
                      GDP         2.703004e+09  2.909340e+09  3.136284e+09
Andorra               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Angola                Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Antigua and Barbuda   Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Arab World            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Argentina             Population  2.162184e+07  2.195393e+07  2.228339e+07
                      GDP         1.827212e+10  2.560525e+10  2.834471e+10
Armenia               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Aruba                 Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Australia             Population  1.095000e+07  1.116700e+07  1.138800e+07
                      GDP         2.149737e+10  2.375406e+10  2.592564e+10
Austria               Population  7.175811e+06  7.223801e+06  7.270889e+06
                      GDP         8.374175e+09  9.169984e+09  9.994071e+09
Azerbaijan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Bahamas, The          Population  1.273310e+05  1.336970e+05  1.400490e+05
                      GDP         2.377428e+08  2.666641e+08  3.003922e+08
Bahrain               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
...                                        ...           ...           ...
United Arab Emirates  Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
United Kingdom        Population  5.365000e+07  5.400000e+07  5.434805e+07
                      GDP         8.544377e+10  9.338760e+10  1.005958e+11
United States         Population  1.892420e+08  1.918890e+08  1.943030e+08
                      GDP         6.386000e+11  6.858000e+11  7.437000e+11
Upper middle income   Population  1.204372e+09  1.232266e+09  1.261069e+09
                      GDP         1.955819e+11  2.144250e+11  2.397244e+11
Uruguay               Population  2.635128e+06  2.665387e+06  2.694535e+06
                      GDP         1.539682e+09  1.975702e+09  1.890769e+09
Uzbekistan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Vanuatu               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Venezuela, RB         Population  9.130346e+06  9.476255e+06  9.824694e+06
                      GDP         1.066338e+10  9.113581e+09  9.602945e+09
Vietnam               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Virgin Islands (U.S.) Population  3.870000e+04  4.130000e+04  4.400000e+04
                      GDP         4.140000e+07  5.380000e+07  6.650000e+07
West Bank and Gaza    Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
World                 Population  3.193947e+09  3.259355e+09  3.326054e+09
                      GDP         1.638187e+12  1.799675e+12  1.959900e+12
Yemen, Rep.           Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia                Population  3.342894e+06  3.449266e+06  3.559687e+06
                      GDP         7.043397e+08  8.226397e+08  1.061200e+09
Zimbabwe              Population  4.140804e+06  4.279561e+06  4.422132e+06
                      GDP         1.159512e+09  1.217138e+09  1.311436e+09

year                                      1966          1967          1968  \
country
Afghanistan           Population  1.014884e+07  1.036860e+07  1.059979e+07
                      GDP         1.400000e+09  1.673333e+09  1.373333e+09
Albania               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria               Population  1.298027e+07  1.335420e+07  1.374438e+07
                      GDP         3.039859e+09  3.370870e+09  3.852147e+09
Andorra               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Angola                Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Antigua and Barbuda   Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Arab World            Population  0.000000e+00  0.000000e+00  1.155571e+08
                      GDP         0.000000e+00  0.000000e+00  2.552596e+10
Argentina             Population  2.260875e+07  2.293220e+07  2.326127e+07
                      GDP         2.863047e+10  2.425667e+10  2.643686e+10
Armenia               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Aruba                 Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Australia             Population  1.165100e+07  1.179900e+07  1.200900e+07
                      GDP         2.725053e+10  3.037854e+10  3.264195e+10
Austria               Population  7.322066e+06  7.376998e+06  7.415403e+06
                      GDP         1.088768e+10  1.157943e+10  1.244063e+10
Azerbaijan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Bahamas, The          Population  1.463640e+05  1.526070e+05  1.586290e+05
                      GDP         3.400000e+08  3.901961e+08  4.449020e+08
Bahrain               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
...                                        ...           ...           ...
United Arab Emirates  Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
United Kingdom        Population  5.464850e+07  5.494360e+07  5.521170e+07
                      GDP         1.070907e+11  1.111854e+11  1.047027e+11
United States         Population  1.965600e+08  1.987120e+08  2.007060e+08
                      GDP         8.150000e+11  8.617000e+11  9.425000e+11
Upper middle income   Population  1.292755e+09  1.323615e+09  1.355381e+09
                      GDP         2.666625e+11  2.766866e+11  2.898954e+11
Uruguay               Population  2.722874e+06  2.750093e+06  2.774771e+06
                      GDP         1.809184e+09  1.597721e+09  1.593675e+09
Uzbekistan            Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Vanuatu               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Venezuela, RB         Population  1.017514e+07  1.052805e+07  1.088200e+07
                      GDP         1.009657e+10  1.047278e+10  1.147091e+10
Vietnam               Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Virgin Islands (U.S.) Population  4.730000e+04  5.080000e+04  5.460000e+04
                      GDP         8.410000e+07  1.154000e+08  1.738000e+08
West Bank and Gaza    Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
World                 Population  3.395866e+09  3.465297e+09  3.535512e+09
                      GDP         2.125397e+12  2.262923e+12  2.440549e+12
Yemen, Rep.           Population  0.000000e+00  0.000000e+00  0.000000e+00
                      GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia                Population  3.674088e+06  3.792864e+06  3.916928e+06
                      GDP         1.239000e+09  1.340639e+09  1.573739e+09
Zimbabwe              Population  4.568320e+06  4.718612e+06  4.874113e+06
                      GDP         1.281750e+09  1.397002e+09  1.479600e+09

year                                      1969      ...               2006  \
country                                             ...
Afghanistan           Population  1.084951e+07      ...       2.518362e+07
                      GDP         1.408889e+09      ...       7.057598e+09
Albania               Population  0.000000e+00      ...       2.992547e+06
                      GDP         0.000000e+00      ...       8.992642e+09
Algeria               Population  1.414444e+07      ...       3.374933e+07
                      GDP         4.257253e+09      ...       1.170273e+11
Andorra               Population  0.000000e+00      ...       8.337300e+04
                      GDP         0.000000e+00      ...       3.536452e+09
Angola                Population  0.000000e+00      ...       1.854147e+07
                      GDP         0.000000e+00      ...       4.178948e+10
Antigua and Barbuda   Population  0.000000e+00      ...       8.346700e+04
                      GDP         0.000000e+00      ...       1.135144e+09
Arab World            Population  1.188239e+08      ...       3.209067e+08
                      GDP         2.817577e+10      ...       1.404190e+12
Argentina             Population  2.360599e+07      ...       3.955875e+07
                      GDP         3.125628e+10      ...       2.626665e+11
Armenia               Population  0.000000e+00      ...       3.002161e+06
                      GDP         0.000000e+00      ...       6.384452e+09
Aruba                 Population  0.000000e+00      ...       1.008300e+05
                      GDP         0.000000e+00      ...       2.421475e+09
Australia             Population  1.226300e+07      ...       2.069790e+07
                      GDP         3.660656e+10      ...       7.468808e+11
Austria               Population  7.441055e+06      ...       8.268641e+06
                      GDP         1.358280e+10      ...       3.343094e+11
Azerbaijan            Population  0.000000e+00      ...       8.484550e+06
                      GDP         0.000000e+00      ...       2.098302e+10
Bahamas, The          Population  1.642500e+05      ...       3.358010e+05
                      GDP         5.281373e+08      ...       7.965588e+09
Bahrain               Population  0.000000e+00      ...       9.408080e+05
                      GDP         0.000000e+00      ...       1.850505e+10
...                                        ...      ...                ...
United Arab Emirates  Population  0.000000e+00      ...       5.171255e+06
                      GDP         0.000000e+00      ...       2.221059e+11
United Kingdom        Population  5.544175e+07      ...       6.084682e+07
                      GDP         1.126769e+11      ...       2.588077e+12
United States         Population  2.026770e+08      ...       2.983799e+08
                      GDP         1.019900e+12      ...       1.385589e+13
Upper middle income   Population  1.388827e+09      ...       2.380136e+09
                      GDP         3.221882e+11      ...       8.620784e+12
Uruguay               Population  2.795044e+06      ...       3.331041e+06
                      GDP         2.004435e+09      ...       1.957946e+10
Uzbekistan            Population  0.000000e+00      ...       2.648825e+07
                      GDP         0.000000e+00      ...       1.703090e+10
Vanuatu               Population  0.000000e+00      ...       2.146350e+05
                      GDP         0.000000e+00      ...       4.393768e+08
Venezuela, RB         Population  1.123549e+07      ...       2.722123e+07
                      GDP         1.192757e+10      ...       1.834775e+11
Vietnam               Population  0.000000e+00      ...       8.331120e+07
                      GDP         0.000000e+00      ...       6.637166e+10
Virgin Islands (U.S.) Population  5.860000e+04      ...       0.000000e+00
                      GDP         2.113000e+08      ...       0.000000e+00
West Bank and Gaza    Population  0.000000e+00      ...       3.406334e+06
                      GDP         0.000000e+00      ...       4.910100e+09
World                 Population  3.609910e+09      ...       6.594722e+09
                      GDP         2.686747e+12      ...       5.107451e+13
Yemen, Rep.           Population  0.000000e+00      ...       2.109397e+07
                      GDP         0.000000e+00      ...       1.908173e+10
Zambia                Population  4.047479e+06      ...       1.238151e+07
                      GDP         1.926399e+09      ...       1.275686e+10
Zimbabwe              Population  5.036321e+06      ...       1.312794e+07
                      GDP         1.747999e+09      ...       5.443896e+09

year                                      2007          2008          2009  \
country
Afghanistan           Population  2.587754e+07  2.652874e+07  2.720729e+07
                      GDP         9.843842e+09  1.019053e+10  1.248694e+10
Albania               Population  2.970017e+06  2.947314e+06  2.927519e+06
                      GDP         1.070101e+10  1.288135e+10  1.204421e+10
Algeria               Population  3.426197e+07  3.481106e+07  3.540179e+07
                      GDP         1.349771e+11  1.710007e+11  1.372110e+11
Andorra               Population  8.487800e+04  8.561600e+04  8.547400e+04
                      GDP         4.010785e+09  4.001349e+09  3.649863e+09
Angola                Population  1.918391e+07  1.984225e+07  2.052010e+07
                      GDP         6.044892e+10  8.417803e+10  7.549238e+10
Antigua and Barbuda   Population  8.439700e+04  8.535000e+04  8.630000e+04
                      GDP         1.289254e+09  1.347350e+09  1.206410e+09
Arab World            Population  3.287666e+08  3.368865e+08  3.450542e+08
                      GDP         1.641666e+12  2.081343e+12  1.798878e+12
Argentina             Population  3.996990e+07  4.038186e+07  4.079864e+07
                      GDP         3.293175e+11  4.037820e+11  3.766279e+11

In [152]:
sales=pd.read_csv(r"F:\4-1 Files\Udemy - Data Analysis with Pandas and Python\1. Installation and Setup\1.1 pandas.zip\salesmen.csv",parse_dates=["Date"])
sales["Salesman"]=sales["Salesman"].astype("category")
sales.head(3)

        Date Salesman  Revenue
0 2016-01-01      Bob     7172
1 2016-01-02      Bob     6362
2 2016-01-03      Bob     5982

In [177]:
sales.pivot(index="Date",columns="Salesman",values="Revenue").head(3)

Salesman     Bob  Dave   Jeb  Oscar  Ronald
Date
2016-01-01  7172  1864  4430   5250    2639
2016-01-02  6362  8278  8026   8661    4951
2016-01-03  5982  4226  5188   7075    2703

In [178]:
fd=pd.read_csv(r"F:\4-1 Files\Udemy - Data Analysis with Pandas and Python\1. Installation and Setup\1.1 pandas.zip\foods.csv")
fd["Gender"]=fd["Gender"].astype("category")
fd["Item"]=fd["Item"].astype("category")
fd.head(3)

  First Name  Gender      City Frequency     Item  Spend
0      Wanda  Female  Stamford    Weekly   Burger  15.66
1       Eric    Male  Stamford     Daily  Chalupa  10.56
2    Charles    Male  New York     Never    Sushi  42.14

In [181]:
fd.pivot_table(index="Gender",columns="Item",values="Spend",aggfunc="mean")

Item       Burger    Burrito    Chalupa      Donut  Ice Cream      Sushi
Gender
Female  49.930488  50.092000  54.635000  49.926316  49.788519  50.355699
Male    49.613919  48.344819  49.186761  43.649565  51.096000  55.614384

In [186]:
s=fd.pivot_table(values="Spend",index=["Gender","Item"],columns=["Frequency","City"],aggfunc="sum")
s.head(3)

Frequency         Daily                        Monthly                        \
City           New York Philadelphia Stamford New York Philadelphia Stamford
Gender Item
Female Burger    262.67       231.68   144.66   171.86       215.05   238.49
       Burrito   224.45       321.57   195.63   122.74        34.28    67.94
       Chalupa    43.19        23.49    95.70   158.37       289.96   161.98

Frequency         Never                          Often   ...        Once  \
City           New York Philadelphia Stamford New York   ...    Stamford
Gender Item                                              ...
Female Burger     97.89       218.97    90.97    94.96   ...       95.05
       Burrito   189.73       382.30   366.34   103.60   ...      168.01
       Chalupa    35.15       121.97   156.36    39.73   ...       40.59

Frequency        Seldom                         Weekly                        \
City           New York Philadelphia Stamford New York Philadelphia Stamford
Gender Item
Female Burger     63.16       409.05    97.53   184.35        32.00   155.02
       Burrito   167.54       198.11   234.49    39.69        62.82   230.91
       Chalupa   160.00       274.51   175.25   171.52        84.41   204.69

Frequency        Yearly
City           New York Philadelphia Stamford
Gender Item
Female Burger    259.30       123.17   307.03
       Burrito    71.26       116.75   172.98
       Chalupa   157.82       504.44   348.16

[3 rows x 24 columns]

In [169]:
s.unstack()

          Spend
Item     Burger  Burrito  Chalupa    Donut Ice Cream    Sushi
Gender
Female  4094.30  4257.82  4152.26  4743.00   4032.87  4683.08
Male    3671.43  4012.62  3492.26  4015.76   4854.12  4059.85

In [179]:
fd.pivot(index="Gender",columns="Item",values="Spend")

ValueError: Index contains duplicate entries, cannot reshape

In [187]:
fd.pivot_table(values="Spend",index=["Gender","Item"],columns="City",aggfunc="count")

City              New York  Philadelphia  Stamford
Gender Item
Female Burger           24            31        27
       Burrito          23            28        34
       Chalupa          19            32        25
       Donut            31            30        34
       Ice Cream        27            32        22
       Sushi            31            30        32
Male   Burger           22            21        31
       Burrito          25            30        28
       Chalupa          25            23        23
       Donut            30            33        29
       Ice Cream        29            41        25
       Sushi            27            28        18

In [188]:
fd.melt()

        variable      value
0     First Name      Wanda
1     First Name       Eric
2     First Name    Charles
3     First Name       Anna
4     First Name    Deborah
5     First Name    Charles
6     First Name       Mark
7     First Name       Paul
8     First Name      Larry
9     First Name      Roger
10    First Name     Samuel
11    First Name     Rachel
12    First Name       Mary
13    First Name       Lori
14    First Name      Henry
15    First Name       Paul
16    First Name      Karen
17    First Name    Frances
18    First Name      Bruce
19    First Name     Bonnie
20    First Name       Anne
21    First Name       Rose
22    First Name       Earl
23    First Name    Phyllis
24    First Name     Gerald
25    First Name      Carol
26    First Name     Dennis
27    First Name  Stephanie
28    First Name      Sarah
29    First Name   Lawrence
...          ...        ...
5970       Spend      11.68
5971       Spend      56.41
5972       Spend      14.13
5973       Spend       1.18
5974       Spend      40.01
5975       Spend       8.38
5976       Spend      95.69
5977       Spend      70.78
5978       Spend      64.28
5979       Spend      19.12
5980       Spend      58.95
5981       Spend      65.19
5982       Spend      35.88
5983       Spend      20.78
5984       Spend      35.74
5985       Spend      70.17
5986       Spend      92.16
5987       Spend       65.7
5988       Spend       69.8
5989       Spend      80.38
5990       Spend      97.89
5991       Spend       8.72
5992       Spend      90.32
5993       Spend      13.79
5994       Spend      98.61
5995       Spend      83.53
5996       Spend      72.88
5997       Spend       5.85
5998       Spend      43.19
5999       Spend      28.36

[6000 rows x 2 columns]